config/routes.rb
Plotbunnysharing::Application.routes.draw do
  devise_for :users
  root 'ideas#index'

  resources :ideas 

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @ideas = Idea.all
  end

  def new 
    @idea = Idea.new
  end

# This method actually creates the idea using the values 
  def create
    current_user.ideas.create(idea_params)
    redirect_to root_path
  end

  def show 
    @idea = Idea.find(params[:id])
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update_attributes(idea_params)
    redirect_to root_path
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to root_path
  end

  private

# This method sucks in the values from the form 
  def idea_params
    params.require(:idea).permit(:title, :summary, :plot, :characters, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Idea Details</h1>
  <%= simple_form_for @idea do |f| %> 
    <%= f.input :title %>
    <%= f.input :summary %>
    <%= f.input :plot %>
    <%= f.input :characters %>
    <%= f.input :notes %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/ideas/index.html.erb
<h1>ALL STORY IDEAS</h1>
<% @ideas.each do |idea| %> 
  <div>
    <h1><%= link_to idea.title, idea_path(idea) %></h1><br />
    <i><%= idea.summary %></i>
  </div>

  <hr />
<% end %>

app/views/ideas/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Idea Details</h1>
  <%= simple_form_for @idea do |f| %> 
    <%= f.input :title %>
    <%= f.input :summary %>
    <%= f.input :plot %>
    <%= f.input :characters %>
    <%= f.input :notes %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/ideas/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1>TITLE:</h1>
<p><%= @idea.title %></p>
<h1>SUMMARY:</h1>
<i><%= @idea.summary %></i>
<h1>PLOT:</h1>
<p><%= @idea.plot %></p>
<h1>CHARACTERS:</h1>
<p><%= @idea.characters %></p>
<h1>NOTES:</h1>
<p><%= @idea.notes %></p>
<div class="pull-left">
    <%= link_to 'Edit', edit_idea_path(@idea), class: 'btn btn-primary' %>
    <%= link_to 'Destroy', idea_path(@idea), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plotbunnysharing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Plot Bunny Sharing', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'New Idea', new_idea_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
        <li><a href="#">Link</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>